### ISSUE TITLE
GPU OOO when folding a >4000 residue protein with colabfold

### ISSUE THREAD

**Issue by KryptoShrimp** [labdao/plex#619]
Requirement already satisfied: py3Dmol in /usr/local/lib/python3.10/dist-packages (2.0.3)
Plex version (v0.9.1) up to date.
Error: get: invalid path "": invalid ipfs path
---------------------------------------------------------------------------
PlexError                                 Traceback (most recent call last)
[<ipython-input-6-a76f0a40ea0e>](https://localhost:8080/#) in <cell line: 6>()
      4 get_ipython().system('pip install py3Dmol')
      5 
----> 6 results = plex_vectorize(completed_io_cid, CoreTools.COLABFOLD_MINI.value)
      7 
      8 print(results)

[/usr/local/lib/python3.10/dist-packages/plex/__init__.py](https://localhost:8080/#) in plex_vectorize(io_path, tool_cid, output_dir, plex_path)
     95 
     96     if outvects == "":
---> 97         raise PlexError("Failed to vectorize IO JSON CID")
     98 
     99     return outvects

PlexError: Failed to vectorize IO JSON CID
If this error persists, please submit an issue at https://github.com/labdao/plex/issues

**Comment by NiklasTR** [comment]
Thank you for sharing this report!

We looked into this and the issue emerged because of a VRAM out-of-memory on our compute infrastructure. I recreated the error on our infrastructure *and* a google collab pro. Both we and google colab use T40 NVIDIA cards that max out at 16GB of VRAM. The protein you want to fold has 4000+ residues which can't be processed on these machines right now. 

We are looking into ways to onboard more heavy-duty compute to the public network. If you know people with sufficient GPU resources, we'd love to talk.
